DetoxMeApp/Models/Detox.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DetoxMeApp.Models
{
    public class Detox
    {
        public int Id { get; set; }

        public string  DetoxQuestion { get; set; }

        public string DetoxAnswer { get; set; }


        public Detox()
        {

        }

    }

}

DetoxMeApp/Models/ErrorViewModel.cs
using System;

namespace DetoxMeApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DetoxMeApp/Controllers/DetoxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DetoxMeApp.Data;
using DetoxMeApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace DetoxMeApp.Controllers
{
    public class DetoxController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DetoxController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Detox
        public async Task<IActionResult> Index()
        {
            return View(await _context.Detox.ToListAsync());
        }

        // GET: Detox/ShowSearchForm
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }

        // POST: Detox/ShowSearchResults
        public async Task<IActionResult>ShowSearchResults(String SearchPhrase)
        {
            return View("Index", await _context.Detox.Where( j=> j.DetoxQuestion.Contains(SearchPhrase)).ToListAsync());
        }

        // GET: Detox/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detox = await _context.Detox
                .FirstOrDefaultAsync(m => m.Id == id);
            if (detox == null)
            {
                return NotFound();
            }

            return View(detox);
        }

        // GET: Detox/Create

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Detox/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DetoxQuestion,DetoxAnswer")] Detox detox)
        {
            if (ModelState.IsValid)
            {
                _context.Add(detox);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(detox);
        }

        // GET: Detox/Edit/5

        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detox = await _context.Detox.FindAsync(id);
            if (detox == null)
            {
                return NotFound();
            }
            return View(detox);
        }

        // POST: Detox/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DetoxQuestion,DetoxAnswer")] Detox detox)
        {
            if (id != detox.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(detox);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DetoxExists(detox.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(detox);
        }

        // GET: Detox/Delete/5

        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detox = await _context.Detox
                .FirstOrDefaultAsync(m => m.Id == id);
            if (detox == null)
            {
                return NotFound();
            }

            return View(detox);
        }

        // POST: Detox/Delete/5

        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var detox = await _context.Detox.FindAsync(id);
            _context.Detox.Remove(detox);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DetoxExists(int id)
        {
            return _context.Detox.Any(e => e.Id == id);
        }
    }
}

DetoxMeApp/Controllers/HomeController.cs
using DetoxMeApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DetoxMeApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DetoxMeApp/Views/Detox/Create.cshtml
@model DetoxMeApp.Models.Detox

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Detox</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DetoxQuestion" class="control-label"></label>
                <input asp-for="DetoxQuestion" class="form-control" />
                <span asp-validation-for="DetoxQuestion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DetoxAnswer" class="control-label"></label>
                <input asp-for="DetoxAnswer" class="form-control" />
                <span asp-validation-for="DetoxAnswer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DetoxMeApp/Views/Detox/Delete.cshtml
@model DetoxMeApp.Models.Detox

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Detox</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DetoxQuestion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DetoxQuestion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DetoxAnswer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DetoxAnswer)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DetoxMeApp/Views/Detox/Details.cshtml
@model DetoxMeApp.Models.Detox

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Detox</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DetoxQuestion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DetoxQuestion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DetoxAnswer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DetoxAnswer)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DetoxMeApp/Views/Detox/Edit.cshtml
@model DetoxMeApp.Models.Detox

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Detox</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="DetoxQuestion" class="control-label"></label>
                <input asp-for="DetoxQuestion" class="form-control" />
                <span asp-validation-for="DetoxQuestion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DetoxAnswer" class="control-label"></label>
                <input asp-for="DetoxAnswer" class="form-control" />
                <span asp-validation-for="DetoxAnswer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DetoxMeApp/Views/Detox/Index.cshtml
@model IEnumerable<DetoxMeApp.Models.Detox>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DetoxQuestion)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DetoxQuestion)
            </td>
            
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

DetoxMeApp/Views/Detox/ShowSearchForm.cshtml
<h4>Search for a Detox</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowSearchResults">

            <div class="form-group">
                <label for="SearchPhrase" class="control-label"></label>
                <input name="SearchPhrase" class="form-control" />
            </div>
            <div class=" form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action=" Index">Back to List</a>
</div>

DetoxMeApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Wilkommen</h1>
    <p><strong>7-Tägige die beste Detox-Kur-Plan!</strong></p>
</div>

DetoxMeApp/Views/Index.cshtml
@page
@model DetoxMeApp.Views.IndexModel
@{
}

DetoxMeApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DetoxMeApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DetoxMeApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Detox" asp-action="Index">Detox</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Detox" asp-action="ShowSearchForm">Search</a>
                        </li>
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DetoxMeApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>